### ISSUE TITLE
Prep for PyPI submission

### ISSUE THREAD

**Issue by jayqi** [drivendataorg/nbautoexport#27]
There's some cleanup we should probably do when ready to submit to PyPI. Off the top of my head:

- [x] choose an OSS license and create a `LICENSE.md` file (closed by #48) 
- [x] go through `MANIFEST.in` and make sure we're including/excluding what we want (closed by #48)
- [x] go through README and clean it up (some instructions might not match recent changes) (closed by #40)

**Comment by jayqi** [comment]
All of these have been addressed.
